version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
